language: python
python: 2.7

install: 
  - pwd
  - ls $HOME
  - .travis/getnrn.sh
  - .travis/getjnml.sh

script: 
  - cd $HOME
  - cd OpenSourceBrain/ghk-nernst/NEURON/
  - python nernstnat_na_k_ca.py
  - ls /tmp